typeset -U path cdpath fpath manpath



for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/dw62gc7w8x36qpwj98lspz1scizwdsss-zsh-5.8/share/zsh/$ZSH_VERSION/help"









# Oh-My-Zsh/Prezto calls compinit during initialization,
# calling it twice causes sight start up slowdown
# as all $fpath entries will be traversed again.


source /nix/store/177386lzzxq97x9lpskkfzgd3v7400w6-zsh-autosuggestions-0.6.4/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Environment variables
. "/home/pablo/.nix-profile/etc/profile.d/hm-session-vars.sh"


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git sudo docker)

ZSH_THEME="agnoster"
source $ZSH/oh-my-zsh.sh






# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"
HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


if [[ $options[zle] = on ]]; then
  . /nix/store/f3l96yifz5cw7392c7j9bw9r7xdyjfga-fzf-0.22.0/share/fzf/completion.zsh
  . /nix/store/f3l96yifz5cw7392c7j9bw9r7xdyjfga-fzf-0.22.0/share/fzf/key-bindings.zsh
fi

export PATH=$PATH:~/.emacs.d/bin/
# Aliases


# Global Aliases

